export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const UPDATE_PAGE_COUNTER = 'UPDATE_PAGE_COUNTER';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_MEMO = 'UPDATE_MEMO';
